services:
  db:
    image: postgres:15-alpine
    container_name: asia-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - asia-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: asia-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/asia_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - asia-network
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: asia-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - asia-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  asia-network:
    driver: bridge